### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by dsever** [amrabed/strace-docker#3]
Hi,

It looks like that strace-docker is something I'm looking for collect system calls from docker instance. So can you please provide me some documentation, like how to install and use it?

Thanks in advance

Dubravko

**Comment by amrabed** [comment]
Installations and Usage documentation is [now added](../commit/c0ddefd034cdb5c378868b54cc90cf6b039d4b6e) to [README.md](../blob/master/README.md)
